### ISSUE TITLE
module not found in react container

### ISSUE THREAD

**Issue by ELzeEdge** [coconup/vanpi-react#1]
Hi coconup,

first of all, thanks a lot for creating this!
The whole nomadpi stack is running on a rpi5 8GB (bookworm)
The nomadpi-react container is always running into an module not found error:

> nomadpi-react-2@0.1.0 start
> react-scripts start
> node:internal/modules/cjs/loader:1145
>  throw err;
> ^
>
> Error: Cannot find module './lib/source-map-generator'
>
> Require stack:
> - /usr/src/app/node_modules/css-minimizer-webpack-plugin/node_modules/source-map/source-map.js
> - /usr/src/app/node_modules/css-minimizer-webpack-plugin/dist/index.js
> - /usr/src/app/node_modules/react-scripts/config/webpack.config.js
> - /usr/src/app/node_modules/react-scripts/scripts/start.js
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
>     at Module._load (node:internal/modules/cjs/loader:983:27)
>     at Module.require (node:internal/modules/cjs/loader:1230:19)
>     at require (node:internal/modules/helpers:179:18)
>     at Object.<anonymous> (/usr/src/app/node_modules/css-minimizer-webpack-plugin/node_modules/source-map/source-map.js:6:30)
>     at Module._compile (node:internal/modules/cjs/loader:1368:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
>     at Module.load (node:internal/modules/cjs/loader:1205:32)
>     at Module._load (node:internal/modules/cjs/loader:1021:12)
>     at Module.require (node:internal/modules/cjs/loader:1230:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/usr/src/app/node_modules/css-minimizer-webpack-plugin/node_modules/source-map/source-map.js',
>     '/usr/src/app/node_modules/css-minimizer-webpack-plugin/dist/index.js',
>     '/usr/src/app/node_modules/react-scripts/config/webpack.config.js',
>     '/usr/src/app/node_modules/react-scripts/scripts/start.js'
>   ]
> }
> Node.js v21.7.3

Have you run into this issue before?

**Comment by coconup** [comment]
Hi @ELzeEdge, no I didn't have this when installing everything on the same hardware. Did the installation go through without errors? You can try removing the `node_modules` directory and the `package-lock.json` file and restarting the container to see if it fixes it:

`rm -rf ~/nomadpi/volumes/nomadpi-react/node_modules`
`rm ~/nomadpi/volumes/nomadpi-react/package-lock.json`

Let me know if this solves it!

**Comment by ELzeEdge** [comment]
Hi @coconup,
it seems like switching to the lite OS with a complete reinstall has fixed my issue. 
Maybe something just went wrong the previous times I tried it.
Thanks for your fast response!

**Comment by coconup** [comment]
nice! Happy to hear :)
